
[build-system]
requires = ["setuptools"]
build-backend = "setuptools.build_meta"


[project]
name = "celery-haystack"
version = "3.0.0"
readme = "README.rst"
dependencies = [
    "django>=1.8",
    "django-appconf>=0.4.1",
    "six",
    "celery>=3.1,<6.0",
    "django-haystack>=2.0,<=3.2.1",
]
